name: python-recipes-api

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:80" #external port / container port
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:80"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=python_recipes
      - DB_USER=dev
      - DB_PASS=dev

  postgres:
    image: postgres:16.4-alpine
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=python_recipes
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev


volumes:
  dev-postgres-data: